backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: project
    label: Project
    folder: content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: project
      - label: Title
        name: title
        widget: string
      - label: Start Date
        name: start_date
        widget: date
      - label: End Date
        name: end_date
        widget: date
      - label: Thumbnail
        name: thumbnail
        widget: image
      - label: Skills
        name: skills
        widget: list
        fields:
          - label: Skill
            name: skill
            widget: string
      - label: Featured
        name: featured
        widget: boolean
        default: false
      - label: Description
        name: description
        widget: markdown
  - name: site_settings
    label: Site Settings
    folder: content/site
    create: false
    slug: "{{slug}}"
    fields:
      - label: Name
        name: name
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Resume Link
        name: resume_link
        widget: string
      - label: About Me
        name: about
        widget: markdown
      - label: About Page Para
        name: aboutPage
        widget: markdown
      - label: Quotes
        name: quotes
        widget: list
        fields:
          - label: Quote
            name: quote
            widget: string
          - label: Author
            name: author
            widget: string
