backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/media"

collections:
  - name: "project"
    label: "Project"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "project"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Start Date"
        name: "date"
        widget: "date"
      - label: "End Date"
        name: "date"
        widget: "date"
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
      - label: "Skills"
        name: "skills"
        widget: "list"
      - label: "Featured"
        name: "featured"
        widget: "boolean"
        default: false
      - label: "Description"
        name: "description"
        widget: "markdown"
  - name: "site_settings"
    label: "Site Settings"
    folder: "content/site"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Resume Link"
        name: "resume_link"
        widget: "string"
      - label: "About Me"
        name: "about"
        widget: "markdown"
      - label: "Quotes"
        name: "quotes"
        widget: "list"
        fields:
          - label: "Quote"
            name: "quote"
            widget: "string"
          - label: "Author"
            name: "author"
            widget: "string"
